### ISSUE TITLE
Null pointer check for ObservableAsProperty

### ISSUE THREAD

**Issue by Emailrus** [kswoll/ReactiveUI.Fody#10]
Hi,

Not sure if I'm doing this correctly, but is it possible to initialize value of a field in ObservableAsProperty?
Or maybe even better to have an ability to generate ObservableAsProperty getter with null check?
Otherwise I'm getting exceptions if I'm trying to read properties before my subscriptions kick in.

Thanks

**Comment by kswoll** [comment]
Not sure what you mean.  Can you illustrate your question with some sample code?  What do you mean by "initialize value of a field" in this context?  And what exceptions are you receiving?

**Comment by Emailrus** [comment]
Here is generic example, it is possible to workaround this by adding some extra states, but that is undesired.
Having an ability to safely call MyProperty before it has its field initialized with ToPropertyEx would be great. I think simplest way to achieve that is by adding null check in generated getter

``` csharp
public class MyViewModel : ViewModelBase
{

    [ObservableAsProperty]
    public extern string MyProperty { get; }

    protected override void OnStart()
    {
        // Called after view is created, but not in constructor
        this.WhenAnyValue(model => model.LoadingProgress)
            .Select(progress => progress.ToString())
            .ToPropertyEx(this, model => model.MyProperty);

    }
}

public class SomeClassThatWrapsViewModel
{
    public SomeClassThatWrapsViewModel(MyViewModel viewModel)
    {
        // No way to check if viewModel has its OnStart called
        var test = viewModel.MyProperty; // Null pointer exception
    }
}
```

**Comment by kswoll** [comment]
Sorry it took so long to get back to you.  But I see.  Idiomatically I always set up my observables in the constructor, but I agree that an NRE is undesirable.  I will create a fix today or tomorrow that addresses your concern.
