### ISSUE TITLE
Build the NuGet libraries in release mode

### ISSUE THREAD

**Issue by calebkiage** [kswoll/ReactiveUI.Fody#12]
The NuGet dlls can't be used on windows store apps because they are built in debug mode. I had an application I was publishing fail certification because of this. It passed after I built the dlls from source in release mode and replaced the NuGet dlls.

**Comment by kswoll** [comment]
Wow, I hadn't realized that Release mode would impact such a scenario.  Thanks for the report!  Latest nuget should fix that.  (might take a few minutes for it to propagate on their servers, but the version would be ReactiveUI.Fody 1.1.25.

**Comment by calebkiage** [comment]
I have tried to update the package but it's removing the reference to ReactiveUI.Fody.Helpers from the project. Version 1.1.10 works properly.

**Comment by calebkiage** [comment]
Adding the reference manually, Fody throws the error:

```
Fody: Could not find a weaver named 'ReactiveUI'. 
If you have nuget package restore turned on you probably need to do a build to download the weavers. 
Alternatively you may have added a weaver to your 'FodyWeavers.xml' and forgot to add the appropriate nuget package.
Perhaps you need to run 'Install-Package ReactiveUI.Fody'. This url may provide more information http://nuget.org/packages/ReactiveUI.Fody/
```

**Comment by kswoll** [comment]
Hmm, sorry about that.  I see what you are saying and can repro locally.  I'll fix.

**Comment by calebkiage** [comment]
Ah, great! Thank you for the timely responses.

**Comment by kswoll** [comment]
Ok, all set.  I've tested the latest version on a sample project and it works fine now.  

I apologize for not testing my change first -- I recently had to recreate my deployment script for appveyor and I evidently screwed up the nuget package process.

**Comment by calebkiage** [comment]
That's alright. Happens to the best of us. The new package version works fine now. Thanks.
