### ISSUE TITLE
Xamarin Studio on OS X cannot run Unit Tests

### ISSUE THREAD

**Issue by carlossless** [kswoll/ReactiveUI.Fody#19]
Hi, I wanted to do a few modifications to this wonderful tool, however I can't seem to manage running the the tests. Any ideas why this might be happening?

Here's the error I've been getting.

```
Can't find custom attr constructor image: /Users/mindw0rk/Projects/HeyJobs/Fody2/ReactiveUI.Fody.Tests/bin/Debug/ReactiveUI.dll mtoken: 0x0a000011
Unhandled loader error: 8, (null) PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (null)
* Assertion: should not be reached at loader.c:299
```

**Comment by kswoll** [comment]
Hi, thanks for the kind words! :)  I don't have a mac handy at the moment, but I noticed the test project had an unnecessary reference to `WindowsBase`, which seems like it might be related to that reference to `PresentationFramework`.  I've removed that reference and published a new version.  Would you mind trying it out and seeing if it fixes your problem?

**Comment by carlossless** [comment]
Actually the problem was related to the Net45 version of ReactiveUI referencing PresentationFramework. I'm trying to get around it by using the Xamarin.Mac10 platform library, but am now getting weird nunit related issues. I'll keep this thread up to date with my progress.
