### ISSUE TITLE
Please Update to RxUI 7

### ISSUE THREAD

**Issue by escamoteur** [kswoll/ReactiveUI.Fody#23]
Hi,

I just had to find out that ReactiveUI.Fody doesn't work with RxUI7

Please help to make it work again.

Thanks a lot
Thomas

**Comment by kswoll** [comment]
Yeah, it's easy to fix -- just need to rebuild the helper assembly against rxui7.  But rxui7 is in beta, right?  So I'm reluctant to update the nuget package to point to an unreleased version of rxui.  Thoughts?

**Comment by escamoteur** [comment]
I was told that

ToProperty has an extra attribute in RxUI 7 which Fody doesn't include in the code it generates, so this causes errors

So I don't know if a rebuild alone is enough.

But you could make a new nuget and mar it as prerelease

**Comment by Qonstrukt** [comment]
A rebuild should be enough, but I think this breaks RxUI 6.5 compatibility, so I'm not sure how you'd go about this the right way.

**Comment by escamoteur** [comment]
why not making a new branch and mark it as prerelease?

**Comment by kswoll** [comment]
The prerelease option sounds good.  I've yet to try that with nuget, so I'll investigate.  Will get this sorted in the next couple days.

**Comment by escamoteur** [comment]
Great!

**Comment by kswoll** [comment]
I think it's all good to go.  I tried it on my test project:

https://www.nuget.org/packages/ReactiveUI.Fody/2.0.61-beta

> Update-Package ReactiveUI.Fody -Pre

Let me know if there are any issues.

**Comment by escamoteur** [comment]
Just tried it it works.
Thanks a lot for this really fast fix

**Comment by kswoll** [comment]
Awesome, glad it's working for you too! :)
