### ISSUE TITLE
ReactiveUI 7 Released

### ISSUE THREAD

**Issue by HeathHopkins** [kswoll/ReactiveUI.Fody#24]
Thanks creating this Fody package.  Reactive 7 was just released on NuGet in the main feed.  When you get a chance, can you update the beta branch's NuGet dependencies to allow reaciveui 7.0.0 instead of 7.0.0.1478039116?

**Comment by kswoll** [comment]
Removed the beta tag now that reactiveui is officially released.  And fixed the dependencies with the help of @butlerpeter.
