### ISSUE TITLE
[ObservableAsProperty] needs to be updated for ReactiveUI version 7.0.0

### ISSUE THREAD

**Issue by xplatsolutions** [kswoll/ReactiveUI.Fody#28]
The [ObservableAsProperty] attribute needs to be updated according to the breaking changes in ReactiveUI version 7.

https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI/ObservableAsPropertyHelper.cs

**Comment by kswoll** [comment]
@xplatsolutions isn't that what the [latest Nuget](https://www.nuget.org/packages/ReactiveUI.Fody/2.0.65) [already addresses](https://github.com/kswoll/ReactiveUI.Fody/commit/8f57b804af9229afa0007ec21711e516f2b6574d)?  If not, can you elaborate?

**Comment by xplatsolutions** [comment]
Not sure why I didn't see this version before :-) I will download and check it out. Thanks man.
