### ISSUE TITLE
Reactive Attribute suggestion

### ISSUE THREAD

**Issue by jcmm33** [kswoll/ReactiveUI.Fody#3]
Might be worth considering adding a parameter to reactive attribute to specify the access modifier for the set property . We have a few scenarios whereby the setting of the property value is internal to the view model and shouldn't be settable by 'outside' classes e.g.

```
public int Value2 { get { return _value2; } private set { this.RaiseAndSetIfChanged(ref _value2, value); } }
```

**Comment by kswoll** [comment]
Hmm, can't you already do this?

```
[Reactive]public int Value2 { get; private set; }
```

That seems to work for me.

**Comment by jcmm33** [comment]
Sorry, its me being completely stupid.

**Comment by kswoll** [comment]
Lol, no worries. :)
