### ISSUE TITLE
Just upgraded to ReactiveUI.Fody 2.0.66

### ISSUE THREAD

**Issue by bradphelan** [kswoll/ReactiveUI.Fody#34]
During building my project I saw

![image](https://cloud.githubusercontent.com/assets/17650/22874296/84feb7a2-f1c5-11e6-86dd-35f6136cdfba.png)

Unfortunately not an opensource project so I can't point you to the sources. Is the stack trace enough for you to figure out what went wrong?

**Comment by kswoll** [comment]
It means it can't find, during the build, the `ReactiveUI.Fody.Helpers` package.  Can you let me know:

* The type of project you are building (.net core, xamarin, standard, etc.)
* Whether the references for your project contain that helpers assembly?

**Comment by kswoll** [comment]
Also, what is the version of .NET (4.5, 4.6, etc.) for the project that is failing?

**Comment by kswoll** [comment]
Finally, if you could set your build log output to be verbose, and include that log, that would be very helpful.
