### ISSUE TITLE
Installing 2.0.66 installs RxUI 7.0 although 7.2 is installed

### ISSUE THREAD

**Issue by escamoteur** [kswoll/ReactiveUI.Fody#36]
Hi,

Installing 2.0.66 installs RxUI 7.0 although 7.2 is installed

Also I observed that that it installas RxUI component and anot only RxUI.Core

Cheers
Thomas

**Comment by kswoll** [comment]
@escamoteur hmm, ok, any thoughts as to why in terms of the nuspec?

**Comment by escamoteur** [comment]
Unfortunately not I'm really not a nuget expert

**Comment by kswoll** [comment]
Hmm, so I'm not seeing this behavior.  I created a vanilla Console application in VS2015, ran:

> Install-Package ReactiveUI

It then installed the latest reactive ui bits.  I then ran:

> Install-Package ReactiveUI.Fody

And this was the output:

> Attempting to gather dependency information for package 'ReactiveUI.Fody.2.0.66' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.5.2'
> Attempting to resolve dependencies for package 'ReactiveUI.Fody.2.0.66' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'ReactiveUI.Fody.2.0.66'
> Resolved actions to install package 'ReactiveUI.Fody.2.0.66'
> Removed package 'Splat.1.4.0' from 'packages.config'
> Successfully uninstalled 'Splat.1.4.0' from ConsoleApplication1
>   GET https://api.nuget.org/packages/fody.1.28.3.nupkg
>   OK https://api.nuget.org/packages/fody.1.28.3.nupkg 4ms
> Installing Fody 1.28.3.
> Adding package 'Fody.1.28.3' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'Fody.1.28.3' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'Fody.1.28.3' to 'packages.config'
> Executing script file 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages\Fody.1.28.3\tools\install.ps1'
> Successfully installed 'Fody 1.28.3' to ConsoleApplication1
>   GET https://api.nuget.org/packages/splat.1.6.0.nupkg
>   OK https://api.nuget.org/packages/splat.1.6.0.nupkg 21ms
> Installing Splat 1.6.0.
> Adding package 'Splat.1.6.0' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'Splat.1.6.0' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'Splat.1.6.0' to 'packages.config'
> Successfully installed 'Splat 1.6.0' to ConsoleApplication1
>   GET https://api.nuget.org/packages/reactiveui.fody.2.0.66.nupkg
>   OK https://api.nuget.org/packages/reactiveui.fody.2.0.66.nupkg 292ms
> Installing ReactiveUI.Fody 2.0.66.
> Adding package 'ReactiveUI.Fody.2.0.66' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'ReactiveUI.Fody.2.0.66' to folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Added package 'ReactiveUI.Fody.2.0.66' to 'packages.config'
> Successfully installed 'ReactiveUI.Fody 2.0.66' to ConsoleApplication1
> Removing package 'Splat.1.4.0' from folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
> Removed package 'Splat.1.4.0' from folder 'c:\users\kirk\documents\visual studio 2015\Projects\ConsoleApplication1\packages'

**Comment by escamoteur** [comment]
Ah, I updated it to the latest version after I already had RxUI updated to 7.2

**Comment by kswoll** [comment]
@escamoteur so is this a non-issue then?  Should I close?  Or are you saying that if RxUI is at 7.2, there's a problem?

**Comment by escamoteur** [comment]
I guess the problem is if RxUI is already installed in V72. and you then update the Fody Package.
But don't spent more time on if if I'm the only one reporting. I thought it would something that you find easily when looking at the nuget spc.

Thanks a lot!
