### ISSUE TITLE
PackageReference csproj may be breaking install script (Weavers.xml)

### ISSUE THREAD

**Issue by SProst** [kswoll/ReactiveUI.Fody#38]
I have new projects based on the Nuget PackageReference rather than packages.config for handling dependencies. I noticed that after this change, due to the way that dependencies are handled, the install script is not executed correctly for adding the Weavers.xml file. Can anyone with VS2017 verify this?

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by kswoll** [comment]
This would be a bug with Fody, no?  Or are you referring to my `KirkFody` project?  (that's a temporary stop gap as I outlined in your other issue)  In any case, it's really trivial to create that file yourself, so that's the direction I'd go if you're still having trouble.
