### ISSUE TITLE
Conflicts with PropertyChanged.Fody because of cecil version

### ISSUE THREAD

**Issue by extesy** [kswoll/ReactiveUI.Fody#39]
`PropertyChanged.Fody` has recently updated the cecil version it is using (https://github.com/Fody/PropertyChanged/commit/379ba81a6146aaedfc63a6ac3378c33a23720dee) and now it conflicts with `ReactiveUI.Fody` which is still using older version of cecil. When both are enabled, `ReactiveUI.Fody` fails to run.

**Comment by extesy** [comment]
@kswoll I'm quite sure that fixing #40 would also fix this problem.

**Comment by kswoll** [comment]
@extesy you can try it now -- I'm still working out some kinks with a different fody package, which is why it's not a public release yet.

> Install-Package ReactiveUI.Fody -Pre

**Comment by kswoll** [comment]
Here ya go:  https://www.nuget.org/packages/ReactiveUI.Fody/2.2.3
