### ISSUE TITLE
Notify about changes in derived properties

### ISSUE THREAD

**Issue by extesy** [kswoll/ReactiveUI.Fody#41]
Basically, just like in the very first example for https://github.com/Fody/PropertyChanged weaver, I have these three properties:

```C#
[Reactive] public int GamesPlayed { get; set; }
[Reactive] public int GamesWon { get; set; }
public int WinRate => Math.Round((double)GamesWon / GamesPlayed * 100);
```

If I try to annotate `WinRate` with `[Reactive]` attribute, your weaver complains that it doesn't have setter so it can't change. Well, that's not correct - it does change when either `GamesWon` or `GamesPlayed` changes.

I would like the weaver to inject notification for derived property `WinRate` into auto-generated notifiers for source properties `GamesWon` and `GamesPlayed`, just like how `PropertyChanged.Fody` does it currently for WPF applications.

**Comment by extesy** [comment]
I think `GetFullDependencies` function implements this: https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/PropertyDataWalker.cs#L81

**Comment by kswoll** [comment]
This is an interesting suggestion.  The one concern I have is it seems limited -- presumably this only works if the property dependencies are declared in the same class?  If so it seems somewhat inconsistent.  I would be open to a PR that implements this, but I suspect I won't have the time for the forseeable future.  Have you considered using an `[ObservableAsPropety]` instead?  i.e.

```
public class Team
{
    [Reactive] public int GamesPlayed { get; set; }
    [Reactive] public int GamesWon { get; set; }
    [ObservableAsProperty]public int WinRate { get; private set; }

    public Team()
    {
        this.WhenAnyValue(x => x.GamesPlayed)
            .CombineLatest(this.WhenAnyValue(x => x.GamesWon), (_, __) => Unit.Default)
            .Select(x => (double)GamesWon / GamesPlayed * 100)
            .ToPropertyEx(this, x => x.WinRate);
    }
}
```

**Comment by extesy** [comment]
Your are right, your suggestion would also work as an alternative, but 3 out of 4 lines there are just boilerplate and would be the same for any other similar property. To avoid such repeated boilerplate is exactly why Fody was created, wasn't it?

As to your concern about dependencies having to be in the same class - I think that should cover 99% of use cases in the MVVM model and as long as limitations are documented, it should be a huge quality of life improvement.

**Comment by kswoll** [comment]
@extesy sure, like I said, I think it's an interesting suggestion and I'm certainly not opposed.  Just don't have the bandwidth personally at the moment.

**Comment by Syrus666** [comment]
@extesy @kswoll I've put together a PR that should tackle basic uses cases of the proposed idea: https://github.com/kswoll/ReactiveUI.Fody/pull/42
