### ISSUE TITLE
Upgraded from 1.1.1 -> 2.2.4 built on ios doesn't work

### ISSUE THREAD

**Issue by fvermeulen** [kswoll/ReactiveUI.Fody#43]
Hey I updated my Fody and ReactiveUI.Fody today from version 1 to the acutal one

Android works (right now a bit slow, have to look, what you changed, maybe I have to update my code) but iOS doesn't work. When I try to build iOS. While building I get this error:

```/Users/xy/dev/universal-app/iOS/MTOUCH: Error MT2002: Failed to resolve assembly: 'ReactiveUI.Fody.Helpers, Version=2.2.4.0, Culture=neutral, PublicKeyToken=null' (MT2002) (App.iOS)```

I use .NET Portable PCL 4.5 - Profile7
Fody-version is 2.0.7

When you need more info, just write it down.

**Comment by fvermeulen** [comment]
could solve all problems with the library

the slowness came from Xamarin :( Sorry

https://forums.xamarin.com/discussion/95275/slow-performance-after-updating-xamarin-studio-to-stable-release-15-2#latest

**Comment by kswoll** [comment]
Ok, glad you got it all sorted! :)
