### ISSUE TITLE
Trouble getting Fody to work

### ISSUE THREAD

**Issue by dbulic** [kswoll/ReactiveUI.Fody#6]
Hi,
I have trouble getting Fody to run its magic after installing it via Nuget. [Reactive] attribute isn't recognized.

> Currently, you need to add ReactiveUI to your FodyWeavers.xml manually.

I updated it so it reads:

```
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <ReactiveUI />
</Weavers>
```

After project rebuild, Fody throws an error:

```
Error       Fody: An unhandled exception occurred:
Exception:
Sequence contains no matching element
StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute() in c:\Dev\ReactiveUI.Fody\ReactiveUI.Fody\ReactiveUIPropertyWeaver.cs:line 27
   at ReactiveUI.Fody.ModuleWeaver.Execute() in c:\Dev\ReactiveUI.Fody\ReactiveUI.Fody\ModuleWeaver.cs:line 24
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
System.Core
TargetSite:
TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])   Util        
```

That's the following line:

```
var reactiveObject = ModuleDefinition.FindType("ReactiveUI", "ReactiveObject", reactiveUI);
```

My ViewModel descends from ReactiveObject.

**Comment by kswoll** [comment]
I think @bradtwurst fixed this.  Can you get the (just updated) latest package from nuget and see if that resolves your issue?

**Comment by dbulic** [comment]
Error message has changed:

```
Error       Fody: An unhandled exception occurred:
Exception:
Could not find assembly: ReactiveUI.Fody.Helpers (mscorlib, PresentationFramework, Meta, System.Xml, ReplicationEngine, Util, System.Data, System, Caliburn.Micro.Platform, Caliburn.Micro, ActiproSoftware.Shared.Wpf, WindowsBase, System.Windows.Interactivity, Shared, BouncyCastle.Crypto, System.Xaml, PresentationCore, ReactiveUI, System.Core, ActiproSoftware.Themes.Metro.Wpf, MetaAdapter, System.Reactive.Linq, System.Reactive.Interfaces)
StackTrace:
   at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute() in c:\Dev\ReactiveUI.Fody\ReactiveUI.Fody\ReactiveUIPropertyWeaver.cs:line 33
   at ReactiveUI.Fody.ModuleWeaver.Execute() in c:\Dev\ReactiveUI.Fody\ReactiveUI.Fody\ModuleWeaver.cs:line 24
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
ReactiveUI.Fody
TargetSite:
Void Execute()
```

**Comment by kswoll** [comment]
Sorry for being slow to get back to you, but that error seems to indicate that your project (that has Fody attached) does not have a reference to the helper assembly provided by ReactiveUI.Fody.  It's supposed to get referenced automatically when you install the nuget package, but let's take a look at your project references.  Can you check to see if there is indeed a reference to that assembly in your project?  If not, perhaps you can try adding it by hand.  It should be in the ReactiveUI.Fody folder in your packages folder; the specific version depends on your project type.  Incidentally, what sort of project is it?  Standard .NET? (if so, what version?)  Mono, iOS, Android?  Thanks!

**Comment by dbulic** [comment]
Sorry for me being late now :)
I'm using .NET 4.5 in a WPF solution, VS2015 RC. Even when I manually add ReactiveUI.Fody.Helpers assembly error stays absolutely the same.
Helper: packages\ReactiveUI.Fody.1.0.51\lib\net45\ReactiveUI.Fody.Helpers.dll
ReactiveUI: packages\reactiveui-core.6.5.0\lib\Net45\ReactiveUI.dll

Not sure if it matters, but when I install package, it's older version. I then need to do Update-Package in Package Manager Console to get them to upgrade to latest version.
Of course, I have to always uninstall ReactiveUI, because it stops me from compiling the solution.
If there is anything I can do to troubleshoot, let me know.

**Comment by kswoll** [comment]
Hmm, I can't imagine why it's not working. Could you send me a zip of a sample project that reproduces the issue?  I would be happy to investigate on my end.

**Comment by pibone** [comment]
Hi,
It happened to me with this setting:
- Xamarin.Forms PCL with ReactiveUI.Fody installed.
- Android without ReactiveUI.Fody
- iOS without ReactiveUI.Fody

Referencing to the package dll itself in both projects (Android, iOS) solved the issue for me.

**Comment by kswoll** [comment]
Huh, sorry for being so slow to respond, but thanks for the info!  I'll see if I can repro and try to figure out what steps would be necessary to prevent that non-ideal experience.

**Comment by ofirgeller** [comment]
Happening to me as well. message is the same. deleting the nuget pack, , re installing, re referencing all fail to change the message for me.

**Comment by kswoll** [comment]
The stack trace of the particular exception that would lead to this should be different than the one you are receiving.  To be absolutely sure we're on the same codebase, would you mind posting the full stack trace?  Tentatively, it seems like the plugin thinks your project doesn't have a dependency on ReactiveUI.  If the stack trace fails to yield any promising clues, the next step would be a project that you could provide that replicates the error.  Let me know how I can help!

**Comment by ofirgeller** [comment]
stack trace:

Error   1   Fody: An unhandled exception occurred:
Exception:
Could not find assembly: ReactiveUI.Fody.Helpers (ReactiveUI, System.ObjectModel, System.Runtime, System.Threading.Tasks, System.Linq.Expressions, System.Reflection, System.Reactive.Core, System.Reactive.Interfaces)
StackTrace:
   at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ReactiveUIPropertyWeaver.cs:line 36
   at ReactiveUI.Fody.ModuleWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ModuleWeaver.cs:line 24
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 164
   at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
ReactiveUI.Fody
TargetSite:
Void Execute()
    Core

project:

https://github.com/ofirgeller/fody-reactiveui-example

**Comment by kswoll** [comment]
@ofirgeller ah, I see the problem.  You are not currently using my plugin, so despite the fact that you have a reference to ReactiveUI.Fody.Helpers, it is not included in your module since you are not referencing that package at all.  If you change your `MainViewModel` so that the property reads like:

```
    [Reactive]
    public string Text { get; set; }
```

It will fix your build error. (It fixes the error because `[Reactive]` is defined in `ReactiveUI.Fody.Helpers` and I depend on their being a reference to a type in that assembly from your code)  I will look into either updating the documentation or making the plugin more resilient to not using it.  Thanks!

**Comment by ofirgeller** [comment]
It would make sense for it not to fail the build just because it is
installed and not used, or at the very least give a better message to work
with.
thanks for finding the answer!
