### ISSUE TITLE
Exception when using ToPropertyEx(this, x => x.myCoolOPAH);

### ISSUE THREAD

**Issue by ghuntley** [kswoll/ReactiveUI.Fody#8]
> Error      Fody: An unhandled exception occurred:
> 
> Exception:
> Sequence contains no elements
> 
> StackTrace:
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
>    at ReactiveUI.Fody.ObservableAsPropertyWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ObservableAsPropertyWeaver.cs:line 57
>    at ReactiveUI.Fody.ModuleWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ModuleWeaver.cs:line 31
>    at lambda_method(Closure , Object )
>    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
>    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
> 
> Source:
> System.Core
> 
> TargetSite:
> TSource Single[TSource](System.Collections.Generic.IEnumerable`1[TSource]) MyCoolApp.Core          

Here's an example which will cause it to throw, PCL Profile111:

```
using ReactiveUI;
using ReactiveUI.Fody.Helpers;

public class MyCoolViewModel()
{
    public extern bool IsLoading { get; }
    public ReactiveCommand<Unit> { get; }

    ctor()
    {
        RefreshCommand = ReactiveCommand.CreateAsyncObservable(x => Whatever());
        RefreshCommand.IsExecuting.ToPropertyEx(this, x => x.IsLoading);
    }
}
```

Using the following packages:

```
<package id="Fody" version="1.29.4" targetFramework="portable45-net45+win8+wpa81" developmentDependency="true" />
<package id="reactiveui" version="6.5.0" targetFramework="portable45-net45+win8+wpa81" />
<package id="ReactiveUI.Fody" version="1.1.8" targetFramework="portable45-net45+win8+wpa81" />
<package id="reactiveui-core" version="6.5.0" targetFramework="portable45-net45+win8+wpa81" />
```

**Comment by kswoll** [comment]
Here's the actual class I used.  Error should be fixed now with the new nuget build:

```
public class MyCoolViewModel : ReactiveObject
{
    [ObservableAsProperty]public extern bool IsLoading { get; }

    public ReactiveCommand<Unit> RefreshCommand { get; }

    public MyCoolViewModel()
    {
        RefreshCommand = ReactiveCommand.CreateAsyncObservable<Unit>(x => null);
        RefreshCommand.IsExecuting.ToPropertyEx(this, x => x.IsLoading);
    }
}
```
